version: "3.7"

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
            TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
            DOWNLOAD_TO_DIR: "./downloads/"
            BOT_TOKEN: "${BOT_TOKEN}"
            USER_ID: "${USER_ID}"
            CHAT_ID: "${CHAT_ID}"
        volumes:
            - ${DOWNLOAD_TO_DIR}:/app/downloads
