version: "3.7"

services:
    bot:
        image: ghcr.io/avibn/telegram-downloader:telethon-migrate
        environment:
            TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
            TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
            BOT_API_DIR: "/var/lib/telegram-bot-api/"
            DOWNLOAD_TO_DIR: "./downloads/"
            BOT_TOKEN: "${BOT_TOKEN}"
            USER_ID: "${USER_ID}"
            CHAT_ID: "${CHAT_ID}"
        volumes:
            - ${DOWNLOAD_TO_DIR}:/app/downloads
        restart: unless-stopped
