# This file is used to run just the local telegram bot-api service
version: "3.7"

services:
    telegram-bot-api:
        image: aiogram/telegram-bot-api:latest
        environment:
            TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
            TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
            TELEGRAM_LOCAL: "${TELEGRAM_LOCAL}"
        volumes:
            - ${BOT_API_DIR}:/var/lib/telegram-bot-api
        ports:
            - 8081:8081
        env_file:
            - .env
